ALTER TABLE loans
ADD COLUMN monthly_principal_repayment NUMERIC(12,2) NOT NULL DEFAULT 0,
ADD COLUMN monthly_interest NUMERIC(12,2) NOT NULL DEFAULT 0,
ADD COLUMN monthly_total_received NUMERIC(12,2) NOT NULL DEFAULT 0,
ADD COLUMN monthly_paid BOOLEAN NOT NULL DEFAULT FALSE;